/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 knife.gltf --transform
Author: masterdome (https://sketchfab.com/masterdome)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/military-knifewip-0c628c349d544041bdf903ce491694fa
Title: military knife(WIP)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/knife-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert2} rotation={[1.165, -0.011, 0.027]} scale={3} dispose={null} />
    </group>
  )
}

useGLTF.preload('/knife-transformed.glb')
